---
Name: meetupdemoconfig
---
# A useless extension
Page:
  extensions:
    - Robbie\MeetupDemo\Extension\PageExtension

# Throw in the injector, why not
SilverStripe\Core\Injector\Injector:
  Player:
    class: Robbie\MeetupDemo\Model\CricketPlayer
